CREATE TABLE `USER` (
	`USER_ID`	VARCHAR(100)	NOT NULL,
	`NAME`	VARCHAR(255)	NULL,
	`PASSWORD`	VARCHAR(255)	NULL,
	`AGE`	INT(10)	NULL,
	`REGION_ID`	INT(10)	NULL,
	`REG_DATE`	DATE	NULL,
	`UPT_DATE`	DATE	NULL,
	`Field`	VARCHAR(255)	NULL
);

CREATE TABLE `USER_GROUP` (
	`USER_ID`	VARCHAR(255)	NOT NULL,
	`GROUP_JD`	INT(10)	NOT NULL,
	`ROLE_ID`	INT(10)	NOT NULL,
	`STATUS`	VARCHAR(10)	NULL
);

CREATE TABLE `ATTENDANCE` (
	`ATTENDANCE_ID`	INT(10)	NOT NULL,
	`SCHEDULE_ID`	INT(10)	NOT NULL,
	`USER_ID`	VARCHAR(255)	NOT NULL,
	`GROUP_JD`	INT(10)	NOT NULL,
	`WORKDAY`	VARCHAR(20)	NULL,
	`STATUS`	VARCHAR(10)	NULL	COMMENT 'STATUS',
	`REG_DATE`	DATE	NULL,
	`UPT_DATE`	DATE	NULL
);

CREATE TABLE `CODE_INFO` (
	`CODE_TYPE`	VARCHAR(10)	NULL,
	`CODE_CODE`	VARCHAR(255)	NULL	COMMENT 'CODE_TYPE',
	`CODE_DETAIL`	VARCHAR(255)	NULL,
	`REG_DATE`	DATE	NULL,
	`UPT_DATE`	DATE	NULL
);

CREATE TABLE `REGION` (
	`REGION_ID`	INT(10)	NOT NULL,
	`REGION_NAME`	VARCHAR(255)	NULL,
	`REG_DATE`	DATE	NULL,
	`UPT_DATE`	DATE	NULL
);

CREATE TABLE `GROUP_REGION` (
	`REGION_ID`	INT(10)	NOT NULL,
	`GROUP_JD`	INT(10)	NOT NULL
);

CREATE TABLE `USER_REGION` (
	`USER_ID`	INT(10)	NOT NULL,
	`REGION_ID`	INT(10)	NOT NULL
);

CREATE TABLE `CATEGORY` (
	`CATEGORY_ID`	INT(10)	NOT NULL,
	`CATEGORY_NAME`	VARCHAR(255)	NULL,
	`REG_DATE`	DATE	NULL,
	`UPT_DATE`	DATE	NULL
);

CREATE TABLE `GROUP` (
	`GROUP_JD`	INT(10)	NOT NULL,
	`CATEGORY_ID`	INT(10)	NOT NULL,
	`GROUP_NAME`	VARCHAR(255)	NULL,
	`MAX_AGE`	INT(10)	NULL,
	`MIN_AGE`	INT(10)	NULL,
	`MAX_CNT`	INT(10)	NULL,
	`STATUS`	VARCHAR(10)	NULL,
	`CHAT_URL`	VARCHAR(255)	NULL,
	`CHAT_PW`	VARCHAR(255)	NULL,
	`START_DATE`	VARCHAR(20)	NULL,
	`REG_DATE`	DATE	NULL,
	`UPT_DATE`	DATE	NULL
);

CREATE TABLE `SCHDULE` (
	`SCHEDULE_ID`	INT(10)	NOT NULL,
	`GROUP_JD`	INT(10)	NOT NULL,
	`CATEGORY_ID`	INT(10)	NOT NULL,
	`WORKDAY`	VARCHAR(255)	NULL,
	`TOTAL_CNT`	INT(10)	NULL,
	`ATTENDANCE_CNT`	INT(10)	NULL,
	`REG_DATE`	DATE	NULL,
	`UPT_DATE`	DATE	NULL
);

CREATE TABLE `NOTICE` (
	`NOTICE_ID`	INT(10)	NOT NULL,
	`USER_ID`	VARCHAR(255)	NOT NULL,
	`GROUP_JD`	INT(10)	NOT NULL,
	`NOTICE_TITLE`	VARCHAR(255)	NULL,
	`CONTENT_URL`	VARCHAR(255)	NULL,
	`TYPE`	VARCHAR(10)	NULL,
	`DEL_YN`	VARCHAR(1)	NULL,
	`REG_DATE`	DATE	NULL,
	`UPT_DATE`	DATE	NULL,
	`Field`	VARCHAR(255)	NULL
);

CREATE TABLE `SCHDULE_DATA` (
	`DATA_ID`	INT(10)	NOT NULL,
	`SCHEDULE_ID`	INT(10)	NOT NULL,
	`GROUP_JD`	INT(10)	NOT NULL,
	`CATEGORY_ID`	INT(10)	NOT NULL,
	`CONTENT_URL`	VARCHAR(255)	NULL,
	`REG_DATE`	DATE	NULL,
	`UPT_DATE`	DATE	NULL
);

CREATE TABLE `ATTACH_SCHEDULE_DATA` (
	`ATTACH_ID`	INT(10)	NOT NULL,
	`DATA_ID`	INT(10)	NOT NULL,
	`ATTACH_TYPE`	VARCHAR(10)	NULL,
	`ATTACH_NAME`	VARCHAR(255)	NULL,
	`ATTACH_URL`	VARCHAR(255)	NULL,
	`REG_DATE`	DATE	NULL,
	`UPT_DATE`	DATE	NULL
);

CREATE TABLE `ROLE` (
	`ROLE_ID`	INT(10)	NOT NULL,
	`ROLE_NAME`	VARCHAR(255)	NULL,
	`REG_DATE`	DATE	NULL,
	`UPT_DATE`	DATE	NULL
);

CREATE TABLE `ACTION_LIST` (
	`ACTION_ID`	INT(10)	NOT NULL,
	`ACTION_NAME`	VARCHAR(255)	NULL,
	`REG_DATE`	DATE	NULL,
	`UPT_DATE`	DATE	NULL
);

CREATE TABLE `ROLE_ACTION_LIST` (
	`ACTION_ID`	INT(10)	NOT NULL,
	`ROLE_ID`	INT(10)	NOT NULL
);

ALTER TABLE `USER` ADD CONSTRAINT `PK_USER` PRIMARY KEY (
	`USER_ID`
);

ALTER TABLE `USER_GROUP` ADD CONSTRAINT `PK_USER_GROUP` PRIMARY KEY (
	`USER_ID`,
	`GROUP_JD`,
	`ROLE_ID`
);

ALTER TABLE `ATTENDANCE` ADD CONSTRAINT `PK_ATTENDANCE` PRIMARY KEY (
	`ATTENDANCE_ID`,
	`SCHEDULE_ID`,
	`USER_ID`,
	`GROUP_JD`
);

ALTER TABLE `REGION` ADD CONSTRAINT `PK_REGION` PRIMARY KEY (
	`REGION_ID`
);

ALTER TABLE `GROUP_REGION` ADD CONSTRAINT `PK_GROUP_REGION` PRIMARY KEY (
	`REGION_ID`,
	`GROUP_JD`
);

ALTER TABLE `USER_REGION` ADD CONSTRAINT `PK_USER_REGION` PRIMARY KEY (
	`USER_ID`,
	`REGION_ID`
);

ALTER TABLE `CATEGORY` ADD CONSTRAINT `PK_CATEGORY` PRIMARY KEY (
	`CATEGORY_ID`
);

ALTER TABLE `GROUP` ADD CONSTRAINT `PK_GROUP` PRIMARY KEY (
	`GROUP_JD`,
	`CATEGORY_ID`
);

ALTER TABLE `SCHDULE` ADD CONSTRAINT `PK_SCHDULE` PRIMARY KEY (
	`SCHEDULE_ID`,
	`GROUP_JD`,
	`CATEGORY_ID`
);

ALTER TABLE `NOTICE` ADD CONSTRAINT `PK_NOTICE` PRIMARY KEY (
	`NOTICE_ID`,
	`USER_ID`,
	`GROUP_JD`
);

ALTER TABLE `SCHDULE_DATA` ADD CONSTRAINT `PK_SCHDULE_DATA` PRIMARY KEY (
	`DATA_ID`,
	`SCHEDULE_ID`,
	`GROUP_JD`,
	`CATEGORY_ID`
);

ALTER TABLE `ATTACH_SCHEDULE_DATA` ADD CONSTRAINT `PK_ATTACH_SCHEDULE_DATA` PRIMARY KEY (
	`ATTACH_ID`,
	`DATA_ID`
);

ALTER TABLE `ROLE` ADD CONSTRAINT `PK_ROLE` PRIMARY KEY (
	`ROLE_ID`
);

ALTER TABLE `ACTION_LIST` ADD CONSTRAINT `PK_ACTION_LIST` PRIMARY KEY (
	`ACTION_ID`
);

ALTER TABLE `ROLE_ACTION_LIST` ADD CONSTRAINT `PK_ROLE_ACTION_LIST` PRIMARY KEY (
	`ACTION_ID`,
	`ROLE_ID`
);

ALTER TABLE `USER_GROUP` ADD CONSTRAINT `FK_USER_TO_USER_GROUP_1` FOREIGN KEY (
	`USER_ID`
)
REFERENCES `USER` (
	`USER_ID`
);

ALTER TABLE `USER_GROUP` ADD CONSTRAINT `FK_GROUP_TO_USER_GROUP_1` FOREIGN KEY (
	`GROUP_JD`
)
REFERENCES `GROUP` (
	`GROUP_JD`
);

ALTER TABLE `USER_GROUP` ADD CONSTRAINT `FK_ROLE_TO_USER_GROUP_1` FOREIGN KEY (
	`ROLE_ID`
)
REFERENCES `ROLE` (
	`ROLE_ID`
);

ALTER TABLE `ATTENDANCE` ADD CONSTRAINT `FK_SCHDULE_TO_ATTENDANCE_1` FOREIGN KEY (
	`SCHEDULE_ID`
)
REFERENCES `SCHDULE` (
	`SCHEDULE_ID`
);

ALTER TABLE `ATTENDANCE` ADD CONSTRAINT `FK_USER_GROUP_TO_ATTENDANCE_1` FOREIGN KEY (
	`USER_ID`
)
REFERENCES `USER_GROUP` (
	`USER_ID`
);

ALTER TABLE `ATTENDANCE` ADD CONSTRAINT `FK_USER_GROUP_TO_ATTENDANCE_2` FOREIGN KEY (
	`GROUP_JD`
)
REFERENCES `USER_GROUP` (
	`GROUP_JD`
);

ALTER TABLE `GROUP_REGION` ADD CONSTRAINT `FK_REGION_TO_GROUP_REGION_1` FOREIGN KEY (
	`REGION_ID`
)
REFERENCES `REGION` (
	`REGION_ID`
);

ALTER TABLE `GROUP_REGION` ADD CONSTRAINT `FK_GROUP_TO_GROUP_REGION_1` FOREIGN KEY (
	`GROUP_JD`
)
REFERENCES `GROUP` (
	`GROUP_JD`
);

ALTER TABLE `USER_REGION` ADD CONSTRAINT `FK_USER_TO_USER_REGION_1` FOREIGN KEY (
	`USER_ID`
)
REFERENCES `USER` (
	`USER_ID`
);

ALTER TABLE `USER_REGION` ADD CONSTRAINT `FK_REGION_TO_USER_REGION_1` FOREIGN KEY (
	`REGION_ID`
)
REFERENCES `REGION` (
	`REGION_ID`
);

ALTER TABLE `GROUP` ADD CONSTRAINT `FK_CATEGORY_TO_GROUP_1` FOREIGN KEY (
	`CATEGORY_ID`
)
REFERENCES `CATEGORY` (
	`CATEGORY_ID`
);

ALTER TABLE `SCHDULE` ADD CONSTRAINT `FK_GROUP_TO_SCHDULE_1` FOREIGN KEY (
	`GROUP_JD`
)
REFERENCES `GROUP` (
	`GROUP_JD`
);

ALTER TABLE `SCHDULE` ADD CONSTRAINT `FK_GROUP_TO_SCHDULE_2` FOREIGN KEY (
	`CATEGORY_ID`
)
REFERENCES `GROUP` (
	`CATEGORY_ID`
);

ALTER TABLE `NOTICE` ADD CONSTRAINT `FK_USER_GROUP_TO_NOTICE_1` FOREIGN KEY (
	`USER_ID`
)
REFERENCES `USER_GROUP` (
	`USER_ID`
);

ALTER TABLE `NOTICE` ADD CONSTRAINT `FK_USER_GROUP_TO_NOTICE_2` FOREIGN KEY (
	`GROUP_JD`
)
REFERENCES `USER_GROUP` (
	`GROUP_JD`
);

ALTER TABLE `SCHDULE_DATA` ADD CONSTRAINT `FK_SCHDULE_TO_SCHDULE_DATA_1` FOREIGN KEY (
	`SCHEDULE_ID`
)
REFERENCES `SCHDULE` (
	`SCHEDULE_ID`
);

ALTER TABLE `SCHDULE_DATA` ADD CONSTRAINT `FK_SCHDULE_TO_SCHDULE_DATA_2` FOREIGN KEY (
	`GROUP_JD`
)
REFERENCES `SCHDULE` (
	`GROUP_JD`
);

ALTER TABLE `SCHDULE_DATA` ADD CONSTRAINT `FK_SCHDULE_TO_SCHDULE_DATA_3` FOREIGN KEY (
	`CATEGORY_ID`
)
REFERENCES `SCHDULE` (
	`CATEGORY_ID`
);

ALTER TABLE `ATTACH_SCHEDULE_DATA` ADD CONSTRAINT `FK_SCHDULE_DATA_TO_ATTACH_SCHEDULE_DATA_1` FOREIGN KEY (
	`DATA_ID`
)
REFERENCES `SCHDULE_DATA` (
	`DATA_ID`
);

ALTER TABLE `ROLE_ACTION_LIST` ADD CONSTRAINT `FK_ACTION_LIST_TO_ROLE_ACTION_LIST_1` FOREIGN KEY (
	`ACTION_ID`
)
REFERENCES `ACTION_LIST` (
	`ACTION_ID`
);

ALTER TABLE `ROLE_ACTION_LIST` ADD CONSTRAINT `FK_ROLE_TO_ROLE_ACTION_LIST_1` FOREIGN KEY (
	`ROLE_ID`
)
REFERENCES `ROLE` (
	`ROLE_ID`
);

